_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./R-50.pkl"
DATASETS:
  TRAIN: ('all_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )   # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  STEPS: (24000, 32000)
  MAX_ITER: 36000
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/t1"
# OWOD:
#   PREV_INTRODUCED_CLS: 0
#   CUR_INTRODUCED_CLS: 20